# -*- coding: utf-8 -*-

[build-system]
requires = ['setuptools>=42', 'wheel', 'setuptools_scm[toml]>=3.4']
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "my_project/version.py"
